- charts/ngrok/README.md
- charts/ngrok/templates/deployment.yaml
- charts/ngrok/values.yaml
I added the ability to manually specify a custom ngrok subdomain (useful for paid ngrok accounts).
> Add ngrok subdomain support

- pkg/version/version.go
- ui/vue.html
I'm exposing podinfo behind an Ingress at the `/podinfo` URL, and this patch is needed for the UI to function correctly.
Thanks!
> Fix the UI XHRs when the webserver is mounted at a non-root URL

- README.md
Hey! Thanks a lot for developing and sharing podinfo. This is so handy ☺️ 
I was following https://github.com/stefanprodan/k8s-podinfo/blob/master/docs/1-deploy.md#using-the-helm-chart and `helm test` failed.
The cause seemed like changes in two endpoints. `POST /write` seems to have changed to `POST /store`, and `GET /read/{hash}` to `GET /store/{hash}`. Here's the fix just for README, according to my observation :)
// I should have fixed `/scripts/ping.sh` as well so that `helm test` passes, but had no time!
> fix(doc): Update README about read/write endpoints

- cmd/podinfo/main.go
- pkg/api/server.go
- pkg/version/version.go
Add `-port-metrics` flag, when specified the Prometheus `/metrics` endpoint will be exposed on that port.
> Add option to run the metrics exporter on a different port

- ui/vue.html
This fixes an error that is preventing the UI from working for me:
```
[Vue warn]: Error in getter for watcher "isDark": "TypeError: Cannot read property 'dark' of undefined"
```
Looks like an API change between vuetify 1.x and 2.x.
> Upgrade to vuetify 2.x

- README.md
- pkg/api/chunked.go
- pkg/api/chunked_test.go
- pkg/api/metrics.go
- pkg/api/server.go
Adds an endpoint that does chunk based encoding. The endpoint just stalls
and eventually returns the stall time.
Similar to the delay endpoint but in a chunked maner.
Fixed up the metrics interceptor to wrap ResponseWriter correctly too.
> Add delayed chunk endpoint

- Makefile
- charts/podinfo/Chart.yaml
- charts/podinfo/README.md
- charts/podinfo/templates/deployment.yaml
- charts/podinfo/values.yaml
- cmd/podinfo/main.go
- kustomize/deployment.yaml
- pkg/api/echo.go
- pkg/api/mock.go
- pkg/api/server.go
- pkg/version/version.go
When calling `/echo`, the backends requests will be run in parallel and the results are aggregated and returned to the caller as a json array.
Example:
```
helm upgrade -i frontend sp/podinfo \
--set backends[0]=http://backend1:9898/echo \
--set backends[1]=http://backend2:9898/echo
```
> Add support for multiple backends

- README.md
- charts/podinfo/Chart.yaml
- charts/podinfo/README.md
- charts/podinfo/templates/linkerd.yaml
- charts/podinfo/values.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
Enable Linkerd per-route metrics by adding a service profile for podinfo API.
> Add Linkerd service profile to Helm chart

- charts/podinfo/templates/deployment.yaml
- charts/podinfo/values.yaml
- cmd/podinfo/main.go
- go.mod
- pkg/api/server.go
`podinfo --h2c` allows upgrading a HTTP/1.1 connection to HTTP/2 Cleartext.
This allows `podinfo` to be used in e.g. a H2C load-test like `echo "GET http://localhost:9898/status/200" | vegeta -h2c`, or a H2C connectivity test like done with `curl -v http2 http://localhost:9898/status/200`.
I have manually verified this to work by running `curl -v --http2` on macOS and seeing the H2C upgrade happens onl when `-h2c` is provided to `podinfo`.
Without `-h2c`:
```
$ curl -v --http2 localhost:9898/status/200
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9898 (#0)
> GET /status/200 HTTP/1.1
> Host: localhost:9898
> User-Agent: curl/7.54.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
>
< HTTP/1.1 200 OK
< …
```
> feat: Add H2C support

- .circleci/config.yml
- e2e/README.md
- e2e/bootstrap.sh
- e2e/install.sh
- e2e/test.sh
CircleCI workflow:
* download go modules
* run unit tests
* build container
* install kubectl, Helm v3 and Kubernetes Kind CLIs
* create local Kubernetes v1.17 cluster with kind
* load podinfo image onto the local cluster
* deploy podinfo with Helm v3
* set the podinfo image to the locally built one
* run integration tests with Helm
> e2e: Update Helm to v3 and Kubernetes to v1.17

- charts/podinfo/Chart.yaml
- charts/podinfo/values.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
Helm chart breaking change due to label selectors changes, use `helm upgrade --force `.
> Release v3.2.2

- charts/podinfo/templates/deployment.yaml
* To handle rare situation of digit-only message like 270 and
avoid associated failure during helm install
```
ReadString: expects " or n, but found 2, error found in #10 byte of ...|,"value":270},
{"name|..., bigger context ...|se"],"env":[{"name":"PODINFO_UI_MESSAGE","value":270},
```
> Quote ui message in deployment template

- .circleci/config.yml
- Dockerfile.base
- Makefile
- deploy/bases/frontend/hpa.yaml
Build and push podinfo base image to Docker Hub after each release. The base image contains a cache of podinfo go modules.
> Push base image to Docker Hub

- README.md
- charts/podinfo/templates/ingress.yaml
- charts/podinfo/templates/linkerd.yaml
- charts/podinfo/templates/tests/fail.yaml
- charts/podinfo/templates/tests/timeout.yaml
- e2e/bootstrap.sh
Changes:
- add cache routes to Linkerd profile
- fix Helm tests 
- update ingress API version to `networking.k8s.io/v1beta1`
- update Kubernetes e2e tests to Kind v0.8.1
> Add cache routes to Linkerd profile

- charts/podinfo/templates/tests/fail.yaml
- charts/podinfo/templates/tests/grpc.yaml
- charts/podinfo/templates/tests/jwt.yaml
- charts/podinfo/templates/tests/service.yaml
- charts/podinfo/templates/tests/timeout.yaml
This reverts the #61 change to use test Jobs, which was premature
since this feature hasn't been back ported to Helm 2 yet, which
leads to the tests not being run there.
It would be possible to use presence of .Capabilities.TillerVersion
to implement tests differently for Helm 2 vs 3, but this seems
not worth the trouble.
> Reverts tests as Jobs

- .github/workflows/cve-scan.yml
- README.md
Add GitHub Action workflow to scan podinfo container image for vulnerabilities using [trivy](https://github.com/aquasecurity/trivy).
> Add CVE scanning with trivy

- pkg/grpc/server.go
**Problem:**
I would like to use a generic gRPC load-tester for canary deployment using podinfo as test service (without requiring to have the protobuf files loaded). 
**Solution:**
Enabling gRPC server reflection protocol allows clients to discover and use the interface as expected.
**Concerns:**
I don't see a reason why it should not be enabled by default. But I am happy to add a switch flag to the arguments list if you prefer that.
> Enable gRPC reflection protocol

- charts/podinfo/templates/deployment.yaml
As otherwise the value will render to `null` for the default chart value due to the `#`.
> Always quote the UI color

- .github/workflows/e2e.yml
- .github/workflows/release.yml
- Dockerfile
Publish multi-arch image for linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64 to GitHub Container Registry.
Registry: `ghcr.io/stefanprodan/podinfo`.
> Publish multi-arch image to GHCR

- .github/actions/release-notes/entrypoint.sh
- .github/workflows/e2e.yml
- cmd/podinfo/main.go
- deploy/README.md
- deploy/kind.sh
- deploy/kind.yaml
- deploy/secure/backend/deployment.yaml
- deploy/secure/backend/hpa.yaml
- deploy/secure/backend/service.yaml
- deploy/secure/common/cluster-issuer.yaml
- deploy/secure/common/namespace.yaml
- deploy/secure/common/reconciler-rbac.yaml
- deploy/secure/common/service-account.yaml
- deploy/secure/frontend/certificate.yaml
- deploy/secure/frontend/deployment.yaml
- deploy/secure/frontend/hpa.yaml
- deploy/secure/frontend/service.yaml
- pkg/api/server.go
* add `secure-port` argument to podinfo
* add `cert-path` argument to podinfo
* add http server for secure port
* normalise http/https server start
* add manifests for example secure-port implementation (relies on cert-manager)
* add script to create a cluster via kind to test podinfo locally (with support for self-signed certs)
Closes: #105
> feat(podinfo): add secure port for end-to-end tls

- .github/workflows/e2e.yml
- charts/podinfo/templates/_helpers.tpl
- charts/podinfo/templates/certificate.yaml
- charts/podinfo/templates/deployment.yaml
- charts/podinfo/templates/service.yaml
- charts/podinfo/templates/tests/tls.yaml
- charts/podinfo/values-secure.yaml
- deploy/kind.sh
- hack/build.sh
- hack/deploy.sh
- hack/e2e.sh
- hack/test.sh
- hack/tiller.sh
* add tls variable block to configure service and pod with secure-port
* add ability to create cert-manager certificate
* add support for host ports (both http and https)
* add helm test for tls port
* add example values for secure-port deployment
- this assumes certificate manager is deployed to the cluster
* pull out script blocks into `hack` path
* update e2e workflow to use scripts in `hack`
* install cert manager and self-signed cluster issuer in e2e
* deploy podinfo with secure port and certificate enabled
* add `hack/e2e.sh` script, which can be used to execute the github
workflow locally
Closes: #107
> feat(charts): add tls support to helm chart

- cmd/podinfo/main.go
Any information in case when config file not exist or path\filename configured incorrectly.
It is not clear now.
Propose: handle such situation and inform about that.
> Issue : silence on config file missing error

- charts/podinfo/templates/ingress.yaml
YAML requires asterisk to be quoted.  
If we want to use wildcard host in the ingress so we put in values.yaml something like
```
ingress:
tls:
- secretName: my-secret-tls
hosts:
- '*.example.com'
```
then Helm removes the quote mark before putting the hosts value in the ingress, so the ingress will have this unquoted and will give error:
```
Error: YAML parse error on podinfo/templates/ingress.yaml: error converting YAML to JSON: yaml: line 21: did not find expected alphabetic or numeric character
```
See same issue : <https://github.com/helm/helm/issues/3936>.
and this PR that fixes it in Helm code: <https://github.com/helm/helm/pull/3956>.
This fix applies the same to podinfo.
> Add quoting support in ingress to allow wildcard domain

- Dockerfile
This PR closes #116:
```
$ docker container run -ti --rm ghcr.io/stefanprodan/podinfo:5.1.2 id app
uid=100(app) gid=65533(nogroup) groups=65533(nogroup),65533(nogroup)
```
fixed `Dockerfile`:
```
$ docker container run -ti --rm podinfo:correct id app
uid=100(app) gid=101(app) groups=101(app),101(app)
```
> Fix adduser param to actually use 'app' group

- charts/podinfo/templates/servicemonitor.yaml
Match labels for service monitor should be `app.kubernetes.io/name=podinfo`, using the `podinfo.selectorLabels` helper for future changes.
> chart: Fix ServiceMonitor matchLabels for service

- charts/podinfo/templates/servicemonitor.yaml
As a matter of best-practice, the ServiceMonitor should only select its own namespace.
> fix(chart): ensure that the servicemonitor only selects its own namespace

- charts/podinfo/templates/deployment.yaml
The connection information for redis does not match the service entry.
> chart: Fix Redis backend url

- charts/podinfo/templates/deployment.yaml
- charts/podinfo/values.yaml
- cmd/podinfo/main.go
- pkg/api/server.go
Useful when demonstrating service mesh functionality as by binding to localhost `--host=127.0.0.1` one can show how traffic needs to be routed via a sidecar proxy. 
Note: Haven't updated any version numbers (app or chart) - happy to do so if needed.
> Add option to bind service to specific host

- charts/podinfo/Chart.yaml
- charts/podinfo/README.md
- charts/podinfo/templates/servicemonitor.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
This PR add the option to add additional labels to the service monitor within the helm chart.
> added additional labels to servicemonitor template

- Makefile
- go.mod
- go.sum
- pkg/api/token.go
- pkg/api/token_test.go
Fix for [CVE-2020-26160](https://avd.aquasec.com/nvd/cve-2020-26160/)
> [CVE-2020-26160] Update dgrijalva/jwt-go to v4

- .github/workflows/e2e.yml
- .github/workflows/test.yml
- charts/podinfo/Chart.yaml
- charts/podinfo/README.md
- charts/podinfo/templates/ingress.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
Signed-off-by: André Bauer <monotek23@gmail.com>
* uses new ingress template which adds option to set ingressClassName and pathtype (disabled by default) introduced by k8s 1.18.x -> https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/
* set kubeversion to 1.19 in chart.yaml
ci update:
* updates kind to use 1.19 images
* updates helm to 3.6.0
* updates kubeval to use another json schem location with more recent content
> chart: Upgrade Ingress to networking.k8s.io/v1 and add ingressClassName

- charts/podinfo/templates/NOTES.txt
Fixes the notes that are printed when the Helm chart is installed with `ingress.enabled: true`.
Before:
```
1. Get the application URL by running these commands:
https://map[host:podinfo.example.com paths:[map[path:/ pathType:ImplementationSpecific]]]
```
After the change:
```
1. Get the application URL by running these commands:
https://podinfo.example.com/
```
The changed part is taken as-is from the output of the `helm create` command of Helm version 3.7.1.
Tested & working as expected.
> Fix ingress URL in Helm chart NOTES.txt

- .github/workflows/release.yml
Push the `./kustomize` manifests with Flux to GHCR and sign them with cosign after each podinfo release.
> Publish OCI artifacts on release with Flux

- .github/workflows/release.yml
Set the revision build arg to the Git SHA in the Docker build step.
> ci: Add revision to Docker build args

- README.md
- charts/podinfo/Chart.yaml
- charts/podinfo/README.md
- charts/podinfo/templates/hpa.yaml
- kustomize/hpa.yaml
- test/deploy.sh
**Breaking change**
- update the `HorizontalPodAutoscaler` definitions to `autoscaling/v2`
- due to HPA API version bump the minimum required version is now Kubernetes 1.23
> Update HPA to autoscaling/v2

- Dockerfile
- Dockerfile.xx
- charts/podinfo/Chart.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
- cue/main.cue
- deploy/bases/backend/deployment.yaml
- deploy/bases/backend/hpa.yaml
- deploy/bases/cache/deployment.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/bases/frontend/hpa.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/frontend/deployment.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
**Breaking change**
To deploy Podinfo on Kubernetes with horizontal pod autoscaling the minimum required version is **Kubernetes v1.23**.
> Release v6.3.0

- cue/podinfo/hpa.cue
- cue/podinfo/servicemonitor.cue
Upgrade HPA to `autoscaling/v2` in CUE definitions
> Update HPA to v2 in CUE definitions

- .github/workflows/e2e.yml
- .github/workflows/release.yml
- README.md
Recently buildkit has added support for generating [SBOMs](https://www.docker.com/blog/generate-sboms-with-buildkit/) and  [SLSA Provenance](https://github.com/moby/buildkit/blob/master/docs/attestations/attestation-storage.md). So we can attach the SBOM and Provenance to our container images using the Docker GH Action.
> build: Enable SBOM and SLSA Provenance

- charts/podinfo/templates/deployment.yaml
- charts/podinfo/values.yaml
Add a `startupProbe` for the deployment. A flag is used to enable it (`probes.startup.enable`) and is false by default. 
The goal is to showcase how to deal with slow-starting applications (although this is not the case with podinfo).
> chart: Add optional startupProbe values 

- .github/workflows/release.yml
Push Timoni module to `oci://ghcr.io/stefanprodan/modules/podinfo` and sign the module with Cosign and GitHub OIDC.
> Publish signed Timoni module to GHCR

- .cosign/README.md
> docs: Verify podinfo release assets with cosign

- timoni/bundles/test.podinfo.cue
- timoni/podinfo/README.md
- timoni/podinfo/debug_tool.cue
- timoni/podinfo/debug_values.cue
- timoni/podinfo/templates/config.cue
- timoni/podinfo/templates/job.cue
- timoni/podinfo/timoni.cue
- timoni/podinfo/values.cue
Add end-to-end tests to the module for verifying that podinfo is accessible from within the cluster.
> timoni: Add connectivity test to module

- pkg/signals/shutdown.go
> Add comment on sleep during graceful shutdown

- .github/workflows/cve-scan.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use `GITHUB_OUTPUT` instead of set-output

- kustomize/deployment.yaml
Added an emptyDir to the kustomzie deployment, otherwise the /store endpoint does not work for storing files.
> Fixes /store endpoint with the kustomize deployment

- charts/podinfo/templates/deployment.yaml
- charts/podinfo/templates/pdb.yaml
- charts/podinfo/values.yaml
Hi there
First of all thank you very much for podinfo! It's such a nice app and I used it heavily in the last couple of days to check app availability during migration testing.
Duing so I found myself looking for config options to specify `topologySpreadConstraints` and `podDisruptionBudget` in the helm chart which I didn't found. They are often used to ensure maximum availability during upgrades.
So here they are ;)
Tests done: only helm template locally
> feat(helm): add topologySpreadConstraints and PDB

- charts/podinfo/README.md
- charts/podinfo/templates/deployment.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
Motivation
- Allow input extraEnvs to input arbitral options
Modification
- add extraEnvs to chart
Verification
- values.entraEnvs
Values.yaml
extraEnvs:
- name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
value: "http://otel:4317"
- name: MULTIPLE_VALUES
value: TEST
$ helm template . -s templates/deployment.yaml
env:
- name: PODINFO_UI_COLOR
value: "#34577c"
- name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
value: http://otel:4317
- name: MULTIPLE_VALUES
value: TEST
> feature(chart): allow extraEnvs to be parst

- charts/podinfo/README.md
- charts/podinfo/templates/deployment.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
Signed-off-by: toyamagu2021 <toyamagu2021@gmail.com>
* Allow input `config` and `config-path`
* Allow input `extraArgs` to input arbitral options
* add `config.name`, `config.path`, and `extraArgs` to chart
* `config.name`, `config.path`
```yaml
config:
path: "."
name: "config.yaml"
```
```
$ helm template . -s templates/deployment.yaml
command:
- ./podinfo
- --port=9898
- --cert-path=/data/cert
- --port-metrics=9797
- --grpc-port=9999
- --grpc-service-name=podinfo
- --level=info
- --random-delay=false
- --random-error=false
- --config-path=.
- --config=config.yaml
```
* `extraArgs`
```
extraArgs:
- --test=test
```
```
$ helm template . -s templates/deployment.yaml
command:
- ./podinfo
- --port=9898
- --cert-path=/data/cert
- --port-metrics=9797
- --grpc-port=9999
- …
```
> feat(chart): allow input config and extraArgs

- Makefile
- go.mod
- go.sum
- pkg/api/http/chunked.go
- pkg/api/http/delay.go
- pkg/api/http/docs/docs.go
- pkg/api/http/docs/swagger.json
- pkg/api/http/docs/swagger.yaml
- pkg/api/http/echo.go
- pkg/api/http/echows.go
- pkg/api/http/env.go
- pkg/api/http/headers.go
- pkg/api/http/info.go
- pkg/api/http/server.go
- pkg/api/http/status.go
- pkg/api/http/store.go
- pkg/api/http/token.go
- pkg/api/http/version.go
Now it is possible to use the swagger webinterface running on a host other than localhost e.g. in docker or kubernetes.
Removed the @host line from pkg/api/server.go and
ran make swagger.
Fixes: #179
> Removed reference to localhost from swagger

- pkg/api/http/echows.go
Only closes the communication channel once the send host timer routine has finished and therefore avoid getting it writing to the channel which was already closed.
Fixes #363 .
> fix: panic when the WebSocket endpoint is under load

- charts/podinfo/README.md
- charts/podinfo/templates/deployment.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
I see it is supported in timoni but missing from the helm chart
> Added support for podSecurityContext in helm chart

- charts/podinfo/templates/NOTES.txt
- charts/podinfo/templates/_helpers.tpl
- charts/podinfo/templates/certificate.yaml
- charts/podinfo/templates/deployment.yaml
- charts/podinfo/templates/hpa.yaml
- charts/podinfo/templates/ingress.yaml
- charts/podinfo/templates/linkerd.yaml
- charts/podinfo/templates/pdb.yaml
- charts/podinfo/templates/service.yaml
- charts/podinfo/templates/servicemonitor.yaml
- charts/podinfo/templates/tests/cache.yaml
- charts/podinfo/templates/tests/fail.yaml
- charts/podinfo/templates/tests/grpc.yaml
- charts/podinfo/templates/tests/jwt.yaml
- charts/podinfo/templates/tests/service.yaml
- charts/podinfo/templates/tests/timeout.yaml
- charts/podinfo/templates/tests/tls.yaml
In this PR I added two things:
- `metadata.namespace` to all (namespaced) resources
- ability to override this field to a custom namespace by adopting the "community standard" `.Values.namespaceOverride`
Some more details:
There are tools which uses Helm only for templating (equivalent to `helm template .`):
- Kustomize (with `--enable-helm`)
- Argo CD
- CI scripts like
- `helm template . | kubeconform ...`
- `helm template . | kyverno apply -f -` (this is what I need for this chart 😄)
While I added the first "feature" to all resources, I thought that I create the common helper inside `_helpers.tpl` and add this to all resources instead of `{{ .Release.Namespace}}`.
I think the Helm chart community is heavily influenced by the Bitnami helm charts, they all support this, and many more.
- …
> feat(helm): Add namespace field to all resources
