- ui/vue.html
sets the bg color as blue for primary and green for canary workloads
> set color based on primary/canary workload

- cmd/podinfo/main.go
- deploy/auto-scaling/podinfo-dep.yaml
- pkg/version/version.go
> Add port validation

- .circleci/config.yml
- charts/podinfo/Chart.yaml
- charts/podinfo/values.yaml
- e2e/README.md
- e2e/build.sh
- e2e/install.sh
- kustomize/deployment.yaml
- pkg/version/version.go
Run the unit tests and build before starting the Kubernetes Kind cluster.
> Release v2.0.2

- README.md
- charts/podinfo/Chart.yaml
- charts/podinfo/README.md
- charts/podinfo/values.yaml
- kustomize/deployment.yaml
- kustomize/service.yaml
- pkg/version/version.go
The v3.0 release adds an implementation of the gRPC Health Checking Protocol.
> Release v3.0.0

- charts/podinfo/Chart.yaml
- charts/podinfo/templates/ingress.yaml
- charts/podinfo/templates/tests/grpc.yaml
- charts/podinfo/templates/tests/jwt.yaml
- charts/podinfo/templates/tests/service.yaml
- charts/podinfo/values.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
- prevent service mesh injection for Helm test pods (Istio, Linkerd, AppMesh)
> Fix Helm tests when running inside a service mesh

- .circleci/config.yml
- Dockerfile
- go.mod
Update CI and Dockerfile to go 1.13
> Update to go 1.13

- Makefile
- cmd/podinfo/main.go
> Fix background colour

- charts/podinfo/README.md
- charts/podinfo/templates/NOTES.txt
- charts/podinfo/templates/deployment.yaml
- charts/podinfo/templates/service.yaml
- charts/podinfo/templates/servicemonitor.yaml
- charts/podinfo/templates/tests/jwt.yaml
- charts/podinfo/templates/tests/service.yaml
- charts/podinfo/values.yaml
> chart: add Prometheus Operator service monitor

- Makefile
- deploy/README.md
- deploy/bases/backend/deployment.yaml
- deploy/bases/backend/hpa.yaml
- deploy/bases/backend/kustomization.yaml
- deploy/bases/backend/service.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/bases/frontend/hpa.yaml
- deploy/bases/frontend/kustomization.yaml
- deploy/bases/frontend/service.yaml
- deploy/overlays/dev/kustomization.yaml
- deploy/overlays/dev/labels.yaml
- deploy/overlays/dev/namespace.yaml
- deploy/overlays/production/kustomization.yaml
- deploy/overlays/production/labels.yaml
- deploy/overlays/production/namespace.yaml
- deploy/overlays/staging/kustomization.yaml
- deploy/overlays/staging/labels.yaml
- deploy/overlays/staging/namespace.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/backend/hpa.yaml
- deploy/webapp/backend/service.yaml
- deploy/webapp/common/namespace.yaml
- deploy/webapp/common/service-account.yaml
- deploy/webapp/frontend/deployment.yaml
- deploy/webapp/frontend/hpa.yaml
- deploy/webapp/frontend/service.yaml
Add demo webapp to showcase multi-env deployments with kustomize.
> Add webapp demo

- charts/podinfo/templates/tests/grpc.yaml
- charts/podinfo/templates/tests/jwt.yaml
- charts/podinfo/templates/tests/service.yaml
Without this "helm.sh/hook-delete-policy": before-hook-creation" does not work.
> Helm 3 tests should be Jobs

- charts/podinfo/README.md
- charts/podinfo/templates/tests/fail.yaml
- charts/podinfo/templates/tests/timeout.yaml
- charts/podinfo/values.yaml
This is to support testing of https://github.com/fluxcd/helm-operator/issues/369.
> Support simulating helm test failure and timeout

- pkg/api/cache.go
- pkg/api/server.go
If the caching server is online, podinfo registers its hostname and version in Redis. The set expires after one minute and it's refreshed every 30 seconds.
> Register hostname and version in cache

- .github/workflows/build.yml
- .github/workflows/push.yml
- Dockerfile
- README.md
- e2e/build.sh
Add Docker buildx release workflow.
Multi-arch image for testing: `stefanprodan/podinfo:multiarch`
Fix: #68
> Push releases to Docker Hub for AMD64, ARM64 and ARM v6/v7

- charts/podinfo/Chart.yaml
- charts/podinfo/values.yaml
- deploy/bases/backend/deployment.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/frontend/deployment.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
v4.0 comes with ARM and ARM64 container images.
> Release 4.0.0

- charts/podinfo/README.md
- charts/podinfo/templates/deployment.yaml
- charts/podinfo/templates/redis/config.yaml
- charts/podinfo/templates/redis/deployment.yaml
- charts/podinfo/templates/redis/service.yaml
- charts/podinfo/values.yaml
Add option to Helm chart for deploying Redis and setting up caching.
> Add Redis deployment to Helm chart

- charts/podinfo/templates/hpa.yaml
- kustomize/hpa.yaml
update apiVersion: autoscaling/v2beta2
> Update HPA to autoscaling/v2beta2

- charts/podinfo/Chart.yaml
- charts/podinfo/README.md
- charts/podinfo/templates/_helpers.tpl
- charts/podinfo/templates/deployment.yaml
- charts/podinfo/templates/hpa.yaml
- charts/podinfo/templates/ingress.yaml
- charts/podinfo/templates/linkerd.yaml
- charts/podinfo/templates/service.yaml
- charts/podinfo/templates/serviceaccount.yaml
- charts/podinfo/templates/servicemonitor.yaml
- charts/podinfo/templates/tests/cache.yaml
- charts/podinfo/templates/tests/fail.yaml
- charts/podinfo/templates/tests/grpc.yaml
- charts/podinfo/templates/tests/jwt.yaml
- charts/podinfo/templates/tests/service.yaml
- charts/podinfo/templates/tests/timeout.yaml
Signed-off-by: André Bauer <monotek23@gmail.com>
The chart now follows the new Kubernetes label recommendations:
<https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/>
> updated chart labels to new helm standard

- .github/workflows/release.yml
- README.md
- charts/podinfo/Chart.yaml
- charts/podinfo/templates/_helpers.tpl
- charts/podinfo/values.yaml
- deploy/bases/backend/deployment.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/frontend/deployment.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
Set the default container registry to GHCR
> Release v5.0.0

- .github/workflows/release.yml
Supported platforms: linux/amd64, linux/arm/v7, linux/arm64
> Drop support for linux/arm/v6

- charts/podinfo/README.md
- charts/podinfo/templates/deployment.yaml
- charts/podinfo/templates/service.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
Changes:
- Add Kubernetes service annotations config option (fix: #114)
- Add security context config option (ref: #122)
- Rearrange values and add more comments
> Helm chart improvements

- README.md
This PR adds a `Continuous Delivery` section to readme to showcase podinfo automated upgrades with Flux v2.
> Add Continuous Delivery section to readme

- .github/workflows/test.yml
- Dockerfile
- Dockerfile.base
- Dockerfile.xx
- Makefile
- charts/podinfo/Chart.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
- deploy/bases/backend/deployment.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/frontend/deployment.yaml
- go.mod
- kustomize/deployment.yaml
- pkg/version/version.go
Build podinfo with Go 1.17 and Alpine 1.15
> Update Go to v1.17

- .github/workflows/release.yml
- README.md
Setup cosign keyless signing using GitHub Actions OIDC.
> Sign container images with cosign and GitHub OIDC

- pkg/api/cache.go
Hey @stefanprodan !
First of all, congratulations on the Flux v2 project, it's been a great experience so far!
I've been reading the documentation and started doing [PoC](https://github.com/mmontes11/flux-tenant-podinfo) to see it in action. Specifically, I was interested in setting up Flux with Sealed Secrets so I've tried to find a real use case scenario:  I'm using a redis with authentication and configured the `--cache`  flag in `podinfo` using a [`Secret`](https://github.com/mmontes11/flux-tenant-podinfo/blob/master/apps/my-cluster/podinfo/release.yaml#L26) that comes from a `SealedSecret`.
I had to do some changes to `podinfo` in order to support this because the `redis.Dial` function used to create the redis connection does not support authentication. Here it is the PR  with the …
> Adapted cache to support redis authentication

- .github/workflows/e2e.yml
- .github/workflows/release.yml
- README.md
Push the podinfo charts to `ghcr.io/stefanprodan/charts/podinfo` and sign them with cosign and GitHub OIDC.
> Published signed Helm charts to GHCR

- charts/podinfo/README.md
- charts/podinfo/templates/deployment.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
- cmd/podinfo/main.go
> Add protocol to Redis URL

- charts/podinfo/Chart.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
- cue/main.cue
- deploy/bases/backend/deployment.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/frontend/deployment.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
> Release 6.1.7

- go.mod
- go.sum
> Update gopkg.in/yaml.v3 to v3.0.1

- .github/workflows/cve-scan.yml
- .github/workflows/e2e.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
> Update GitHub Actions workflows

- charts/podinfo/Chart.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
- cue/main.cue
- deploy/bases/backend/deployment.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/frontend/deployment.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
This is the first release with podinfo manifests being published to GHCR as Flux OCI artifacts.
> Release 6.2.0

- charts/podinfo/README.md
- charts/podinfo/templates/serviceaccount.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
Add image pull secret to helm chart.
Closes #149
> feat(helm): added imagePullSecrets to serviceAccount

- charts/podinfo/Chart.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
- cue/main.cue
- deploy/bases/backend/deployment.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/frontend/deployment.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
> Release v6.2.3

- charts/podinfo/README.md
- charts/podinfo/templates/ingress.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
This PR adds the option to add additional labels to the ingress within the helm chart
> Added additionalLabels option for ingress in helm chart

- .github/workflows/e2e.yml
- timoni/bundles/test.podinfo.cue
- timoni/podinfo/README.md
- timoni/podinfo/templates/config.cue
- timoni/podinfo/templates/deployment.cue
- timoni/podinfo/templates/ingress.cue
- timoni/podinfo/templates/service.cue
- timoni/podinfo/templates/servicemonitor.cue
- timoni/podinfo/test_values.cue
- Add UI configuration for setting the background color, greeting message and backend URL
- Add dedicated port for metrics scraping
- Add e2e tests for Timoni module
> Timoni module improvements 

- README.md
- charts/podinfo/Chart.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
- deploy/bases/backend/deployment.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/frontend/deployment.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
- timoni/podinfo/values.cue
This version introduces a [Timoni](https://timoni.sh) module for deploying podinfo to Kubernetes clusters.
> Release v6.5.0

- charts/podinfo/Chart.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
- deploy/bases/backend/deployment.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/frontend/deployment.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
- timoni/podinfo/values.cue
Include new OCI artifact format compatible with [Timoni](https://timoni.sh) v0.14
> Release 6.5.1

- charts/podinfo/Chart.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
- deploy/bases/backend/deployment.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/frontend/deployment.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
- timoni/podinfo/values.cue
Fix for CVE-2023-39325 and CVE-2023-38545
> Release 6.5.2

- charts/podinfo/Chart.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
- deploy/bases/backend/deployment.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/frontend/deployment.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
- timoni/podinfo/values.cue
This patch release comes with connectivity tests for the podinfo [Timoni](https://timoni.sh) module.
> Release 6.5.3

- Dockerfile
- Dockerfile.xx
> Update Alpine to 3.19

- charts/podinfo/Chart.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
- deploy/bases/backend/deployment.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/frontend/deployment.yaml
- kustomize/deployment.yaml
- kustomize/kustomization.yaml
- pkg/version/version.go
- timoni/podinfo/values.cue
> Release v6.6.2

- deploy/bases/backend/deployment.yaml
- deploy/bases/frontend/deployment.yaml
> fix(deploy): add protocol to Redis URL

- .github/workflows/test.yml
- timoni/podinfo/cue.mod/module.cue
Adapt module to cope with breaking changes in CUE v0.9
> Set CUE version in Timoni module

- charts/podinfo/Chart.yaml
- charts/podinfo/values-prod.yaml
- charts/podinfo/values.yaml
- deploy/bases/backend/deployment.yaml
- deploy/bases/frontend/deployment.yaml
- deploy/webapp/backend/deployment.yaml
- deploy/webapp/frontend/deployment.yaml
- kustomize/deployment.yaml
- pkg/version/version.go
- timoni/podinfo/values.cue
> Release 6.7.1

- pkg/api/http/logging.go
As possible implementation for the feature request in #387 
I don't think it needs to be more advanced than the supplied patch.
Fix: #387
> feat(logging): add trace_id to http request debug logs

- .github/workflows/cve-scan.yml
- README.md
Switch to https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
> Run CVE scan with govulncheck

- charts/podinfo/values-prod.yaml
Make values-prod.yaml work without values.yaml
> chart: Fix values-prod standalone use-case
